### PR TITLE
Info: Rewrite document to table-style

### PR DESCRIPTION
**Pull request by Luashine**
It's part of my #3 proposal. Please tell me what you think, then I will improve formatting before merging. Some table cells would love some line breaks!

If it's alright, I will continue with the other documents.

I've also noted that the old description seemed to be actually wrong in a few places around the middle of the spec. I had implemented a parser around Hodor's description earlier so I'm pretty confident it is correct. Not that I explored any advnced features like item tables...

I've included other links (all that I know of) to cross-check, if anyone's interested.

----

It is mostly a translation of Hodor's description (it seemed pretty
close to current document in wording).

Sources used:

- Main: https://xgm.guru/p/wc3/w3-file-format
- https://www.wc3maps.com/InsideTheW3M.html
- https://github.com/stijnherfst/HiveWE/wiki/war3map.w3i---Map-Info

Potential sources:

- Not available there: https://github.com/inwc3/wc3libs/tree/master/wc3libs_doc/src/specs/bin
- https://www.hiveworkshop.com/threads/parsing-metadata-from-w3m-w3x-w3n.322007/
- https://www.hiveworkshop.com/threads/list-of-official-patches-for-warcraft-3.322919/

### CODE REVIEW

**Comment by Luashine** [comment]
Here're the CSV files I've worked with and then converted to Markdown tables with https://www.tablesgenerator.com/markdown_tables After this gets merged, the master copy will become the .md document here.

[wc3i.csv](https://github.com/ChiefOfGxBxL/WC3MapSpecification/files/9718107/wc3i.csv)
[wc3i-flags.csv](https://github.com/ChiefOfGxBxL/WC3MapSpecification/files/9718108/wc3i-flags.csv)
[wc3i-playerdata.csv](https://github.com/ChiefOfGxBxL/WC3MapSpecification/files/9718109/wc3i-playerdata.csv)
[wc3i-teamdata.csv](https://github.com/ChiefOfGxBxL/WC3MapSpecification/files/9718110/wc3i-teamdata.csv)
[wc3i-team-flags.csv](https://github.com/ChiefOfGxBxL/WC3MapSpecification/files/9718111/wc3i-team-flags.csv)
[wc3i-custom-upgrades.csv](https://github.com/ChiefOfGxBxL/WC3MapSpecification/files/9718112/wc3i-custom-upgrades.csv)
[wc3i-custom-tech.csv](https://github.com/ChiefOfGxBxL/WC3MapSpecification/files/9718113/wc3i-custom-tech.csv)
[wc3i-randomunittables.csv](https://github.com/ChiefOfGxBxL/WC3MapSpecification/files/9718114/wc3i-randomunittables.csv)
[wc3i-randomitemtables.csv](https://github.com/ChiefOfGxBxL/WC3MapSpecification/files/9718115/wc3i-randomitemtables.csv)

**Comment by Luashine** [comment]
@ChiefOfGxBxL hey do you have time to review and accept the PR? If not, I will continue with changes in my fork.

**Review by ChiefOfGxBxL — APPROVED** [review]
This looks fantastic. Thank you for organizing all this information!

**Comment by ChiefOfGxBxL** [comment]
@Luashine My apologies for the delay. I've reviewed the changes and approved them! Great job and thank you!

**Pull request merged**
